development:
  sessions:
    default:
      database: chat_api_develop
      hosts:
        - localhost:27017
  options:
    raise_not_found_error: false

test:
  sessions:
    default:
      database: chat_api_test
      hosts:
        - localhost:27017
  options:
    raise_not_found_error: false