development:
  sessions:
    default:
      database: chat_api_develop
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: chat_api_test
      hosts:
        - localhost:27017